# Generated by Django 4.2.3 on 2023-09-03 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact_delete_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='earbud1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('image', models.ImageField(upload_to='Downloads')),
                ('price', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('available', models.BooleanField(default=True)),
                ('desc', models.TextField()),
            ],
        ),
    ]
