# Generated by Django 4.2.3 on 2023-09-04 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_admindata_delete_earbud1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='admindata',
        ),
    ]
